//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_info
    {
        public int order_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public cartItem[] items { get; set; }
        public string medicine_list { get; set; }
        public decimal total_price { get; set; }
    }
}
